# osx_image: xcode9.1 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c
xcode_project: JSONDecodeKit.xcodeproj # path to your xcodeproj folder
xcode_scheme: JSONDecodeKit
podfile: pod # Disable `pod install`
osx_image: xcode9.1
git:
  depth: 1
  submodules: false
branches:
  only:
    - master
env:
  global:
  - RELEASE=Debug
  - SCHEME=JSONDecodeKit
  matrix:
    - SDK=macosx
      DESTINATION='platform=OS X,arch=x86_64'

    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=11.1,name=iPhone X'
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus'
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=9.0,name=iPhone 6'
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=8.1,name=iPhone 4S'
script:
  - set -o pipefail
  - echo $DESTINATION, $RELEASE
  - xcodebuild -project JSONDecodeKit.xcodeproj -scheme $SCHEME -configuration $RELEASE -sdk $SDK -destination "$DESTINATION" clean build test | xcpretty
#clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)