# osx_image: xcode9.1 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c
xcode_project: JSONDecodeKit.xcodeproj # path to your xcodeproj folder
xcode_scheme: JSONDecodeKit
podfile: pod # Disable `pod install`
osx_image: xcode10.2
git:
  depth: 1
  submodules: false
branches:
  only:
    - master
env:
  global:
  - RELEASE=Debug
  - SCHEME=JSONDecodeKit
  matrix:
    - SDK=macosx
      DESTINATION='platform=OS X,arch=x86_64'

    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=11.3,name=iPhone X'
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus'
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=12.2,name=iPhone 6'
    # Did find: /usr/lib/libauto.dylib: mach-o, but not built for iOS simulator
    # https://stackoverflow.com/questions/55389080/xcode-10-2-failed-to-run-app-on-simulator-with-ios-10
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=12.2,name=iPhone 6'

    # - SDK=appletvsimulator
    #   DESTINATION='platform=tvOS Simulator,OS=11.1,name=Apple TV 1080p'
    # - SDK=appletvsimulator
    #   DESTINATION='platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p'
    # - SDK=appletvsimulator
    #   DESTINATION='platform=tvOS Simulator,OS=9.0,name=Apple TV 1080p'

    # - SDK=watchsimulator
    #   DESTINATION='platform=watchOS Simulator,OS=4.1,name=Apple Watch - 42mm'
    # - SDK=watchsimulator
    #   DESTINATION='platform=watchOS Simulator,OS=3.2,name=Apple Watch - 42mm'
    # - SDK=watchsimulator
    #   DESTINATION='platform=watchOS Simulator,OS=2.0,name=Apple Watch - 42mm'

script:
  - set -o pipefail
  - echo $DESTINATION, $RELEASE
  - instruments -s devices
  - xcodebuild -project JSONDecodeKit.xcodeproj -scheme $SCHEME -configuration $RELEASE -sdk $SDK -destination "$DESTINATION" clean build test | xcpretty
#clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)